### ISSUE TITLE
Price-matching others in regards to internal clustering indices

### ISSUE THREAD

**Issue by BrandonKMLee** [Simon-Bertrand/Clusters-Features#1]
https://github.com/Simon-Bertrand/Clusters-Features/blob/main/ClustersFeatures/src/_score_index.py

Papers in question:
- http://www2.uaem.mx/r-mirror/web/packages/clusterCrit/vignettes/clusterCrit.pdf
- http://csjournals.com/IJCSC/PDF6-2/53.%20Kp2.pdf
- https://www.semanticscholar.org/paper/Understanding-of-Internal-Clustering-Validation-Liu-Li/f504e1c8fd0fb7c19c73a5759a5fa369131c573e/figure/6

**Comment by Simon-Bertrand** [comment]
Dear,

These papers are defining correctly the different index.

If you want to see which papers i used to create the library, I recommand you to check the documentation at the section "Score" on this link : https://simonbertrand.pages.unistra.fr/Clusters-Features/index.html#score

Really appreciated, 
BERTRAND Simon.

**Comment by BrandonKMLee** [comment]
There are other indices that does not seem to appear in this library that I would like to point out for the record.
- [ ] Baker-Hubert Gamma
- [ ] Ksq DetW Index
- [ ] Log Det Ratio
- [ ] Log SS Ratio
- [ ] Tau Index

**Comment by Simon-Bertrand** [comment]
BrandomKMLee,

The Baker-Hubert Gamma has a very high complexity, so I choosed not to implement it because it will be very long to compute with image datasets. (Since we have to compare all pairs of observations with all others).

Ksq DetW Index and Tau Index have not been implemented for similar reasons.

Log Det Ratio et Log SS Ratio are just a logarithmic version of Det Ratio and SS Ratio that are implemented.

As a trainee in the ICube laboratory, France, I created this library to fulfil the objectives of the laboratory. Unfortunately, it is no longer maintained, but it is open to receive proposals for modifications.

Thanks you,
BERTRAND Simon.
